### PR TITLE
Make source_code truly optional

### PR DESCRIPTION
**Pull request by keegan-shirel**
### Description of your changes

Differentiate between Lineage and LineageWithSource in ingest_csv.py to allow lineage both with and without source code.

Currently, if an ingested csv file has a row with no source code, or a custom lineage v1 file is converted with `migrate_source_code=False`, it will create an object in `lineage.json` like

```
  [
     {
        "src": {},
        "trg": {},
        "source_code": null
     }
  ]
```

The `source_code` property being null results in this error

```
harvester.error.ShowcaseClientError: To resolve the error, please visit our Troubleshooting documentation: https://support.collibra.com/hc/en-us/articles/13453781015063. Showcase returning client error: 
com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
info: ERRORS FOR SCHEMA lineage
    level: \"info\"
warning: the following keywords are unknown and will be ignored: [$defs]
    level: \"warning\"
    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}
    domain: \"syntax\"
    ignored: [\"$defs\"]
error: instance type (null) does not match any allowed primitive type (allowed: [\"object\"])
    level: \"error\"
    schema: {\"loadingURI\":\"#\",\"pointer\":\"/properties/source_code\"}
    instance: {\"pointer\":\"/source_code\"}
    domain: \"validation\"
    keyword: \"type\"
    found: \"null\"
    expected: [\"object\"]
---  END MESSAGES  ---
```

Due to the [lineage schema](https://github.com/collibra/lin-sqldep/blob/main/custom-lineage-scanner/src/main/resources/schema/lineage_schema.json) requiring the `source_code` property to be of `"type": "object."` The lineage schema could be modified to allow `"type": ["object", "null"]` but because `lineage.json` files are only required to have `src` and `trg` properties, I believe changing the helper scripts to completely omit `source_code` if it's empty is less impactful overall.

---

### JIRA reference

None

---

### Impact Analysis

This change handles a particular case that was not being handled before so overall hopefully makes the code more resilient. Existing functionality should not be impacted.

---

#### Checklist

- [x] I have performed a self-review of my code
- [x] My code follows the contribution guidelines of this project
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kristofvancoillie** [comment]
Thanks for the PR, great to see the contribution! I am not a fan however of adding a separate model for this as this makes it less user friendly for the consumers. I would prefer to handle this by using a custom serializer perhaps so it's transparent for the customer. What do you think?

**Comment by keegan-shirel** [comment]
@kristofvancoillie I'm not super familiar with Pydantic, but after your comment I read a little more and think [model exclude](https://docs.pydantic.dev/latest/concepts/serialization/#model-and-field-level-include-and-exclude) and setting `exclude_none=True` when dumping the `Lineage` model might be a more elegant solution.

I will try it out. If it works, would you prefer a new PR or something like reset on this branch?

**Comment by kristofvancoillie** [comment]
Probably a new PR makes more sense, thx for looking into this and let me know if I can help

**Comment by kristofvancoillie** [comment]
Closing as there is another one with better implementation

**Pull request closed without merging**
